config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :home, only: :index

  resources :folders, except: [:new, :edit] do
    member do
      post 'create', as: :new_inner
      get  :manage
    end

    resources :access_permits, only: [:create, :update, :destroy]
  end

  resources :files, only: [:destroy] do
    post :upload, on: :collection

    member do
      get  :download
      post :toggle_lock
    end
  end

  resource :current_user, only: [:update], controller: :current_user do
    collection do
      get   :profile
      put   :update_password
      patch :update_password
    end
  end

  resource :control_panel, only: :show, controller: :control_panel do
    resources :users, except: :show do
      member do
        put   :update_password
        patch :update_password
      end
    end

    resources :contacts, only: [:index, :create, :destroy] do
      member do
        post :mark_as_processed
        post :mark_as_unprocessed
      end
    end
  end

  root 'home#index'
end

app/models/folder.rb
class Folder < ApplicationRecord
  acts_as_paranoid

  belongs_to :creator, class_name: 'User'
  belongs_to :owner,   class_name: 'User'

  has_many :assets, dependent: :destroy
  has_many :access_permits, as: :resource, dependent: :destroy
  has_many :users, through: :access_permits

  COMMON_OPTS = { through: :access_permits, source: :user }.freeze
  has_many :readers,  -> { merge(AccessPermit.reader)  }, COMMON_OPTS
  has_many :writers,  -> { merge(AccessPermit.writer)  }, COMMON_OPTS
  has_many :managers, -> { merge(AccessPermit.manager) }, COMMON_OPTS

  acts_as_tree dependent: :destroy

  validates_presence_of   :name
  validates_uniqueness_of :name, scope: :parent_id, case_sensitive: false

  before_validation :set_owner_id

  after_update :sync_ancestors_updated_at
  after_touch  :sync_ancestors_updated_at

  before_destroy :ensure_no_locked_file_is_destroyed, prepend: true

  def root?
    false
  end

  def assets_size
    assets.sum(&:file_size)
  end

  def has_locked_file?
    assets.any?(&:locked?)
  end

  def created_by?(user)
    creator == user
  end

  def readable_by?(user)
    owner?(user) || reader?(user) || writer?(user) || manager?(user)
  end
  alias accessible_by? readable_by?

  def writable_by?(user)
    owner?(user) || writer?(user) || manager?(user)
  end

  def manageable_by?(user)
    owner?(user) || manager?(user)
  end

  def owner?(user)
    owner_id == user.id
  end

  private

  def reader?(user)
    user.in?(readers) || ancestors.any? { |a| a.readable_by?(user) }
  end

  def writer?(user)
    user.in?(writers) || ancestors.any? { |a| a.writable_by?(user) }
  end

  def manager?(user)
    user.in?(managers) || ancestors.any? { |a| a.manageable_by?(user) }
  end

  def set_owner_id
    self.owner_id = parent.present? ? parent.owner_id : creator_id
  end

  def ensure_no_locked_file_is_destroyed
    return unless self_and_descendants.any?(&:has_locked_file?)

    msg = 'Não é possível efetuar esta ação pois existem arquivos trancados ' \
          'nas pastas a serem excluídas'
    errors[:base] << msg
    throw :abort
  end

  def sync_ancestors_updated_at
    ancestors.where('updated_at < ?', updated_at)
             .update_all(updated_at: updated_at)
  end
end

app/models/log/folder.rb
module Log
  class Folder < ApplicationRecord
    belongs_to :folder, class_name: '::Folder'
    belongs_to :user

    serialize :recorded_changes, Hash

    before_save :ignore_timestamps!

    private

    def ignore_timestamps!
      recorded_changes.delete('created_at')
      recorded_changes.delete('updated_at')
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < BaseController
  before_action :load_folder, only: %i[destroy update]
  before_action :load_decorated_folder, only: %i[show manage]

  def index
    @folder = FolderDecorator.decorate(RootFolder.new(current_user))
    render :show
  end

  def manage
    authorize @folder
  end

  def show
    authorize @folder
  end

  def create
    @folder = Folder.new(folder_params.merge(creator: current_user))
    authorize @folder

    if @folder.save
      FoldersLogService.folder_created(folder: @folder, user: current_user)

      flash[:notice] = 'Pasta criada com sucesso!'
      redirect_to redirect_path
    else
      flash[:error] = @folder.errors.full_messages
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    authorize @folder

    if @folder.update(folder_params)
      FoldersLogService.folder_updated(folder: @folder, user: current_user)
      flash[:notice] = 'Nome atualizado com sucesso!'
    else
      flash[:error] = @folder.errors.full_messages
    end

    redirect_back(fallback_location: redirect_path)
  end

  def destroy
    authorize @folder

    if @folder.destroy
      FoldersLogService.folder_destroyed(folder: @folder, user: current_user)

      flash[:notice] = 'Pasta excluída com sucesso!'
      redirect_to redirect_path
    else
      flash[:error] = @folder.errors.full_messages
      redirect_back(fallback_location: redirect_path)
    end
  end

  private

  def redirect_path
    @folder.parent.present? ? @folder.parent : root_path
  end

  def folder_params
    params.require(:folder).permit(:parent_id, :name)
  end

  def load_decorated_folder
    load_folder unless @folder
    @folder = @folder.decorate
  end

  def load_folder
    @folder = Folder.where(id: params[:id]).first
    resource_not_found! if @folder.blank?
  end
end

app/views/folders/_breadcrumb.html.erb
<ol class="breadcrumb">
  <% unless folder.root? %>
    <li><%= link_to 'Raiz', root_url %></li>
  <% end %>

  <% folder.ancestors.reverse.select { |f| f.accessible_by?(current_user) }.each do |folder| %>
    <li><%= link_to folder.name, folder_path(folder) %></li>
  <% end %>

  <li class='text-lg'><%= folder.name %></li>
</ol>

app/views/folders/_file.html.erb
<div class="folders-items">
  <div class="row">
    <div class="col-xs-3 col-sm-5 folders-prop">
      <% if policy(file).download? %>
        <%= link_to download_file_path(file), download: file.original_name, target: '_blank' do %>
          <%= file.icon %><%= file.original_name %>
        <% end %>
      <% end %>
      <% if policy(file).destroy? %>
        <%= link_to file_path(file), data: { :confirm => 'Tem certeza que deseja apagar este arquivo?' }, :method => :delete, style: 'color: #B11414', title: 'Excluir arquivo' do %>
        <i class="fa fa-fw fa-lg fa-trash-o"></i>
        <% end %>
      <% end %>
      <input type="hidden" class='file-id' value='<%= file.id %>'/>
      <% if policy(file).toggle_lock? %>
        <%= link_to toggle_lock_file_path(file), method: :post, style: "color: #{file.locked? ? '#B11414' : '#E58C00'}", title: "#{file.locked? ? 'Destrancar' : 'Trancar'} arquivo" do %>
          <i class="fa fa-fw fa-lg <%= file.locked? ? 'fa-lock' : 'fa-unlock' %>"></i>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-3 col-sm-2 folders-prop"><%= file.size %></div>
    <div class="col-xs-3 col-sm-2 folders-prop"><%= file.author %></div>
    <div class="col-xs-3 col-sm-3 folders-prop"><%= file.last_modified %></div>
  </div>
</div>

app/views/folders/_folder.html.erb
<div class="folders-items">
  <div class="row">
    <div class="col-xs-3 col-sm-5 folders-prop">
      <%= link_to folder do %>
        <%= folder.icon %><%= folder.name %>
      <% end %>

      <% if policy(folder).manage? %>
        <%= link_to manage_folder_path(folder), title: 'Gerenciar pasta', style: 'color: #E58C00;', class: 'margin-l-sm' do %>
          <i class="fa fa-fw fa-lg fa-cog"></i>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-3 col-sm-2 folders-prop"><%= folder.size %></div>
    <div class="col-xs-3 col-sm-2 folders-prop"><%= folder.author %></div>
    <div class="col-xs-3 col-sm-3 folders-prop"><%= folder.last_modified %></div>
  </div>
</div>

app/views/folders/_folder_content.html.erb
<div class="folders-header">
  <div class="row">
    <div class="col-xs-3 col-sm-5">Nome</div>
    <div class="col-xs-3 col-sm-2">Tamanho</div>
    <div class="col-xs-3 col-sm-2">Criada por</div>
    <div class="col-xs-3 col-sm-3">Modificada em</div>
  </div>
</div>
<% folders.each do |folder| %>
  <%= render partial: 'folder', locals: { folder: folder } %>
<% end %>

<% files.each do |file| %>
  <%= render partial: 'file', locals: { file: file } %>
<% end %>

app/views/folders/_new.html.erb
<!-- Modal -->
<div class='modal fade bs-example-modal-sm' id='<%= modal_id %>' tabindex='-1' role='dialog' aria-labelledby='myModalLabel'>
  <div class='modal-dialog modal-sm' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      </div>
      <%= form_tag folder.new_folder_path do %>
        <div class='modal-body'>
          <%= hidden_field_tag 'folder[parent_id]', parent_id %>
          <div class='form-group'>
            <%= label_tag 'folder_name', 'Nome da pasta:' %>
            <%= text_field_tag 'folder[name]', nil, class: 'form-control' %>
          </div>
        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
          <%= submit_tag 'Criar pasta', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/folders/_upload_btn.html.erb
<%= form_tag upload_files_path, id: 'uploaded_file_form', multipart: true, style: 'display: inline-block;', class: ' margin-v-md' do |f| %>
  <%= hidden_field_tag 'asset[folder_id]', folder.id unless folder.root? %>
  <%= hidden_field_tag 'asset[original_name]', '' %>
  <%= hidden_field_tag 'id', '', id: 'id-to-be-replaced' %>
  <%= label_tag 'asset_uploaded_file', class: 'btn btn-primary' do %>
    <span id='upload-btn-content'>Upload</span>
    <%= file_field_tag 'asset[uploaded_file]', style: 'display: none;'  %>
  <% end %>
<% end %>

<%= content_for :js do %>
  var submitUploadFileForm = function() {
    $('#uploaded_file_form').submit();
  };

  $('#uploaded_file_form').on('change', '#asset_uploaded_file', function() {
    var field    = $(this)
    var fileName = field.val().replace(/.*[\/\\]/, '');
    $('#asset_original_name').val(fileName);

    fileWithSameName = $("a[download='" + fileName + "']");
    if(fileWithSameName.length) {
      var fileId  = fileWithSameName.siblings('.file-id').val()
      var idField = $('#id-to-be-replaced');
      idField.val(fileId);

      if(!confirm('Deseja sobrescrever o arquivo "' + fileName + '"?')){
        idField.val('');
        field.val('');
        return;
      }
    }

    field.parent().addClass('disabled');
    field.siblings('#upload-btn-content').html(
      'Enviando <i class="fa fa-spinner fa-pulse fa-lg fa-fw"></i>'
    );

    submitUploadFileForm();
    field.prop('disabled', 'disabled');
  });
<% end %>

app/views/folders/manage.html.erb
<div class='flex-container horizontal'>
  <div class='flex-item padding-xxl'>
    <div class='panel panel-default margin-b-o padding-xxl'>
      <h1 class='margin-t-xs'>Gerenciar Pasta</h1>
      <div class='row'>
        <div class='col-md-4'>
          <div class='well padding-xxl'>
            <h2 class='margin-t-o'>Dados Gerais:</h2>

            <table class='table'>
              <tr>
                <th>Nome:</th>
                <th>Criada por:</th>
              </tr>
              <tr>
                <td><%= @folder.name %></td>
                <td><%= @folder.creator.name %></td>
              </tr>
            </table>

            <div class='divider xl'></div>

            <% if policy(@folder).edit? %>
              <%= form_for @folder do |f| %>
                <div class='form-group'>
                  <%= f.label :folder_name, 'Nome da pasta:' %>
                  <div class='flex-container'>
                    <div class='flex-item'>
                      <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class='flex-item fixed padding-l-lg'>
                      <%= submit_tag 'Atualizar', class: 'btn btn-primary' %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>

          <% if policy(@folder).destroy? %>
            <%= link_to folder_path(@folder), data: { :confirm => "Todas as pastas e arquivos contidos nesta pasta também serão apagados!\n\nDeseja continuar?" }, :method => :delete, class: 'btn btn-danger btn-lg btn-block margin-v-xl', title: 'Excluir pasta' do %>
              <i class='fa fa-fw fa-lg fa-trash-o'></i>
              Excluir
            <% end %>
          <% end %>
        </div>

        <div class='col-md-8'>
          <div class='border-md padding-xxl'>
            <h2 class='margin-t-o'>
              Permissões:
              <button id='open-modal' type='button' class='btn btn-primary margin-v-md'>Criar Nova</button>
            </h2>

            <div class='row folders-header'>
              <div class='hidden-xs col-sm-6'>Usuário</div>
              <div class='hidden-xs col-sm-3'>Nível de Acesso</div>
              <div class='hidden-xs col-sm-3'>Opções</div>
            </div>

            <div class='row folders-items'>
              <div class='hidden-xs col-sm-6'><%= @folder.creator.name %></div>
              <div class='hidden-xs col-sm-3'>Criador</div>
            </div>

            <% @folder.access_permits.order_by_user_name.each do |permit| %>
              <%= render partial: 'permissions/permit_detail', locals: { permit: permit.decorate, user: permit.user } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%= link_to 'Voltar', :back, class: 'btn btn-default btn-lg margin-v-lg' %>
  </div>
</div>

<%= content_for :body_bottom do %>
  <%= render partial: 'permissions/new', locals: { resource: @folder, modal_id: @folder.modal_id } %>
<% end %>

<%= content_for :js do %>
  $('#open-modal').on('click', function() {
    $('#<%= @folder.modal_id %>').modal('toggle', $(this));
  })
<% end %>

app/views/folders/show.html.erb
<div class="flex-container horizontal">
  <div class="flex-item padding-xxl">
    <div class="panel panel-default margin-b-o padding-xxl">
      <%= render partial: 'breadcrumb', locals: { folder: @folder } %>

      <% if policy(@folder).write? %>
        <button id='open-modal' type='button' class='btn btn-primary margin-v-md'>Criar Pasta</button>
        <%= content_for :body_bottom do %>
          <%= render partial: 'new', locals: { folder: @folder, parent_id: @folder.id, modal_id: @folder.modal_id } %>
        <% end %>

        <%= render partial: 'upload_btn', locals: { folder: @folder } %>
        <%= content_for :js do %>
          $('#open-modal').on('click', function() {
            $('#<%= @folder.modal_id %>').modal('toggle', $(this));
          })

          $(document).on('shown.bs.modal', function (e) {
            var modal = $(e.target);
            modal.find('#folder_name').focus();
          })
        <% end %>
      <% end %>

      <%= @folder.display_content %>
    </div>
  </div>
</div>