config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :home, only: :index

  resources :folders, except: [:new, :edit] do
    member do
      post 'create', as: :new_inner
      get  :manage
    end

    resources :access_permits, only: [:create, :update, :destroy]
  end

  resources :files, only: [:destroy] do
    post :upload, on: :collection

    member do
      get  :download
      post :toggle_lock
    end
  end

  resource :current_user, only: [:update], controller: :current_user do
    collection do
      get   :profile
      put   :update_password
      patch :update_password
    end
  end

  resource :control_panel, only: :show, controller: :control_panel do
    resources :users, except: :show do
      member do
        put   :update_password
        patch :update_password
      end
    end

    resources :contacts, only: [:index, :create, :destroy] do
      member do
        post :mark_as_processed
        post :mark_as_unprocessed
      end
    end
  end

  root 'home#index'
end

app/models/log/user.rb
module Log
  class User < ApplicationRecord
    belongs_to :target, class_name: '::User'
    belongs_to :user

    serialize :recorded_changes, Hash

    before_save :ignore_timestamps!
    before_save :ignore_password!

    private

    def ignore_timestamps!
      recorded_changes.delete('created_at')
      recorded_changes.delete('updated_at')
    end

    def ignore_password!
      recorded_changes.delete('encrypted_password')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :timeoutable

  has_many :folders, foreign_key: :creator_id
  has_many :assets
  has_many :asset_locks
  has_many :access_permits
  has_many :shared_folders, through: :access_permits,
                            source: :resource,
                            source_type: 'Folder'

  validates_presence_of :name
  validates_presence_of :password_confirmation, on: :create,
                                                if: -> { :password }

  USER_LEVELS = %i[read_only regular super].freeze
  enum user_level: USER_LEVELS

  def admin?
    super || super?
  end
end

app/controllers/users_controller.rb
class UsersController < ControlPanelController
  before_action :init_user, only: %i[new create]
  before_action :load_user, except: %i[index new create]
  before_action :authorize_user, except: [:index]

  def index
    authorize current_user
    @users = User.all.order(:name).decorate
  end

  def new; end

  def edit; end

  def create
    attrs = permitted_attributes(@user).merge(psw_default_params)

    if @user.update_attributes(attrs)
      UsersLogService.user_created(target: @user, user: current_user)

      msg = 'Usuário criado com sucesso! A senha inicial é "123456". ' \
            'Por favor altere-a agora ou instrua o novo usuário a '    \
            'alterá-la no primeiro acesso.'

      flash[:notice] = msg
      redirect_to control_panel_users_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_back(fallback_location: control_panel_users_path)
    end
  end

  def update
    if @user.update_attributes(permitted_attributes(@user))
      UsersLogService.user_updated(target: @user, user: current_user)

      flash[:notice] = 'Usuário atualizado com sucesso!'
      redirect_to control_panel_users_path
    else
      flash[:error] = @user.errors.full_messages
      redirect_back(fallback_location: control_panel_users_path)
    end
  end

  def update_password
    if @user.update_attributes(permitted_attributes(@user))
      sign_in(current_user, bypass: true)
      UsersLogService.user_password_updated(target: @user, user: current_user)

      flash[:notice] = 'Senha atualizada com sucesso!'
      redirect_to control_panel_users_path
    else
      flash[:error] = @user.errors.full_messages
      redirect_back(fallback_location: control_panel_users_path)
    end
  end

  def destroy
    if @user.destroy
      UsersLogService.user_destroyed(target: @user, user: current_user)

      flash[:notice] = 'Usuário apagado com sucesso!'
      redirect_to control_panel_users_path
    else
      flash[:error] = @user.errors.full_messages
      redirect_back(fallback_location: control_panel_users_path)
    end
  end

  protected

  def init_user
    @user ||= User.new
  end

  def load_user
    @user ||= User.where(id: params[:id]).first
  end

  def authorize_user
    authorize @user
  end

  private

  def psw_default_params
    psw = '123456'
    { password: psw, password_confirmation: psw }
  end
end

app/helpers/user_helper.rb
module UserHelper
  def translate_user_level(user_level)
    case String(user_level).downcase
    when 'read_only' then 'Somente leitura'
    when 'regular'   then 'Usuário regular'
    when 'super'     then 'Administrador'
    else
      raise "Value \"#{user_level}\" not mapped for translation"
    end
  end
end

app/views/users/_form.html.erb
<%= form_for user, form_opts do |f| %>
  <div class='row'>
    <div class='col-sm-6 col-md-4 col-lg-3'>
      <div class='form-group'>
        <%= f.label :name, 'Nome:' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class='col-sm-6 col-md-4 col-lg-3'>
      <div class='form-group'>
        <%= f.label :email, 'Email:' %>
        <%= f.text_field :email, class: 'form-control', disabled: !current_user.admin? %>
      </div>
    </div>
    <% if manage_admin_status %>
      <div class='col-sm-6 col-md-4 col-lg-3'>
        <div class='form-group'>
          <%= f.label :user_level, 'Nível de acesso:' %>
          <%= f.select :user_level, options_for_select(User::USER_LEVELS.map { |lv| [translate_user_level(lv), lv] }, selected: user.user_level), {}, class: 'form-control' %>
        </div>
      </div>
    <% end %>
  </div>

  <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
<% end %>

app/views/users/_password_form.html.erb
<%= form_for user, form_opts do |f| %>
  <div class='row'>
    <% if require_current_password %>
      <div class='col-sm-6 col-md-4 col-lg-3'>
        <div class='form-group'>
          <%= f.label :current_password, 'Senha atual:' %>
          <%= f.password_field :current_password, class: 'form-control', style: 'color:transparent;' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class='row'>
    <div class='col-sm-6 col-md-4 col-lg-3'>
      <div class='form-group'>
        <%= f.label :password, 'Nova Senha:' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-6 col-md-4 col-lg-3'>
      <div class='form-group'>
        <%= f.label :password_confirmation, 'Confirme a nova Senha:' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>

  <%= f.submit 'Atualizar Senha', :class => 'btn btn-primary' %>
<% end %>

<%= content_for :js do %>
  setTimeout(function() {
    var pswInput = $('#user_current_password');
    pswInput.attr('value', '');
    pswInput.val('');
    pswInput.removeAttr('style');
  }, 200);
<% end %>

app/views/users/edit.html.erb
<h2 class='margin-t-xs'>Editar Usuário</h2>

<div class='divider no-margin'></div>

<h2 class='margin-t-xs'><small>Dados pessoais:</small></h2>
<%= render partial: 'form', locals: { user: @user, manage_admin_status: true, form_opts: { url: control_panel_user_path(@user) } } %>

<div class='divider xl'></div>

<h2 class='margin-t-o'><small>Atualizar a Senha:</small></h2>
<%= render partial: 'password_form', locals: { user: @user, require_current_password: false, form_opts: { url: update_password_control_panel_user_path(@user) } } %>

<%= content_for :js do %>
  $('#link-to-users').addClass('active');
<% end %>

app/views/users/index.html.erb
<h2 class='margin-t-xs'>
  Usuários
  <%= link_to 'Criar novo', new_control_panel_user_path, class: 'btn btn-primary' %>
</h2>

<div class='row folders-header hidden-xs hidden-sm'>
  <div class='col-md-3'>Nome</div>
  <div class='col-md-3'>Email</div>
  <div class='col-md-3'>Admin?</div>
</div>

<% @users.each do |user| %>
  <div class='row folders-items'>
    <div class='col-md-3'>
      <span class='hidden-md hidden-lg text-bold'>Nome: </span>
      <%= user.name %>
    </div>
    <div class='col-md-3'>
      <span class='hidden-md hidden-lg text-bold'>Email: </span>
      <%= user.email %>
    </div>
    <div class='col-md-3'>
      <span class='hidden-md hidden-lg text-bold'>Admin? </span>
      <%= user.admin_to_pt %>
    </div>
    <div class='col-md-3'>
      <% if policy(user).edit? %>
        <%= link_to edit_control_panel_user_path(user), title: 'Editar usuário' do %>
          <span style='color: #E58C00;'>
            <i class='fa fa-pencil fa-fw fa-lg'></i>
          </span>
        <% end %>
      <% end %>
      <% if policy(user).destroy? %>
        <%= link_to control_panel_user_path(user), data: { :confirm => "Tem certeza que deseja apagar este usuário?" }, :method => :delete, style: 'color: #B11414', title: 'Excluir usuário' do %>
          <i class="fa fa-fw fa-lg fa-trash-o"></i>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<%= content_for :js do %>
  $('#link-to-users').addClass('active');
<% end %>

app/views/users/new.html.erb
<h2 class='margin-t-xs'>Criar Usuário</h2>

<div class='divider no-margin'></div>

<h2 class='margin-t-xs'><small>Dados pessoais:</small></h2>
<%= render partial: 'form', locals: { user: @user, manage_admin_status: true, form_opts: { url: control_panel_users_path } } %>

<%= content_for :js do %>
  $('#link-to-users').addClass('active');
<% end %>

app/views/users/profile.html.erb
<div class='flex-container horizontal'>
  <div class='flex-item padding-xxl'>
    <div class='panel panel-default margin-b-o padding-xxl'>
      <h1 class='margin-t-xs'>Meu Perfil</h1>

      <div class='divider no-margin'></div>

      <h3>Dados Pessoais:</h3>
      <%= render partial: 'form', locals: { user: @user, manage_admin_status: false, form_opts: { url: current_user_path } } %>

      <div class='divider xl'></div>

      <h3>Atualizar a Senha:</h3>
      <%= render partial: 'password_form', locals: { user: @user, require_current_password: true, form_opts: { url: update_password_current_user_path } } %>
    </div>
  </div>
</div>