config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :home, only: :index

  resources :folders, except: [:new, :edit] do
    member do
      post 'create', as: :new_inner
      get  :manage
    end

    resources :access_permits, only: [:create, :update, :destroy]
  end

  resources :files, only: [:destroy] do
    post :upload, on: :collection

    member do
      get  :download
      post :toggle_lock
    end
  end

  resource :current_user, only: [:update], controller: :current_user do
    collection do
      get   :profile
      put   :update_password
      patch :update_password
    end
  end

  resource :control_panel, only: :show, controller: :control_panel do
    resources :users, except: :show do
      member do
        put   :update_password
        patch :update_password
      end
    end

    resources :contacts, only: [:index, :create, :destroy] do
      member do
        post :mark_as_processed
        post :mark_as_unprocessed
      end
    end
  end

  root 'home#index'
end

app/views/permissions/_access_level_description.html.erb
<div class="alert alert-warning">
  <h4 class='margin-t-o'>Sobre o campo <b>Nível de acesso</b></h4>

  <p><b>LEITURA</b> permite ao usuário a visualização do conteúdo da pasta e de suas pastas internas, bem como o download de qualquer arquivo contido nas mesmas.</p>
  <p><b>ESCRITA</b> permite, além do exposto acima, que o usuário crie pastas e arquivos na pasta compartilhada e suas sub pastas, bem como atualizar qualquer arquivo ali contido.</p>
  <p><b>GERENCIAR</b> permite ao usuário controle total sobre a pasta compartilhada. Torna-se possível ao usuário apagar arquivos e pastas internas, apagar ou editar a própria pasta compartilhada, assim como gerenciar as permissões de acesso da mesma.</p>
</div>

app/views/permissions/_edit.html.erb
<!-- Modal -->
<div class='modal fade bs-example-modal-sm' id='<%= modal_id %>' tabindex='-1'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class="modal-title">Editar Permissão</h4>
      </div>
      <%= form_for [permit.resource, permit] do |f| %>
        <div class='modal-body'>
          <div class='form-group'>
            <%= f.label :permission_user_id, 'Usuário:' %>
            <%= f.select :user_id, options_for_select(User.order(:name).map { |u| [u.name, u.id] }, selected: permit.user_id), {}, class: 'form-control', disabled: :disabled %>
          </div>

          <div class='form-group'>
            <%= f.label :permission_user_id, 'Nível de acesso:' %>
            <%= f.select :access_level, options_for_select(AccessPermit::ACCESS_LEVELS.map { |lv| [translate_access_level(lv), lv] }, selected: permit.access_level), {}, class: 'form-control' %>
          </div>

          <%= render partial: 'permissions/access_level_description' %>

        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
          <%= submit_tag 'Salvar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/permissions/_new.html.erb
<!-- Modal -->
<div class='modal fade bs-example-modal-sm' id='<%= modal_id %>' tabindex='-1'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class="modal-title">Nova Permissão</h4>
      </div>
      <%= form_tag folder_access_permits_path(resource) do %>
        <div class='modal-body'>
          <%= hidden_field_tag 'access_permit[resource_id]', resource.id %>
          <%= hidden_field_tag 'access_permit[resource_type]', resource.object_class.name %>
          <div class='form-group'>
            <%= label_tag 'access_permit_user_id', 'Usuário:' %>
            <%= select_tag 'access_permit[user_id]', options_from_collection_for_select(User.order(:name), 'id', 'name'), include_blank: 'Selecione um usuário', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= label_tag 'access_permit_access_level', 'Nível de acesso:' %>
            <%= select_tag 'access_permit[access_level]', options_for_select(AccessPermit::ACCESS_LEVELS.map { |lv| [translate_access_level(lv), lv] }), include_blank: 'Selecione o nível de acesso', class: 'form-control' %>
          </div>

          <%= render partial: 'permissions/access_level_description' %>

        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
          <%= submit_tag 'Salvar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/permissions/_permit_detail.html.erb
<div class='row folders-items'>
  <div class='col-sm-6'><%= user.name %></div>
  <div class='col-sm-3'><%= permit.access_level_translated %></div>
  <div class='col-sm-3'>
    <%= link_to folder_access_permit_path(permit.resource, permit), data: { :confirm => "Tem deseja que deseja remover esta permissão de acesso?" }, :method => :delete, style: 'color: #B11414', class: 'margin-l-md', title: 'Excluir permissão de acesso' do %>
      <i class="fa fa-fw fa-lg fa-trash-o"></i>
    <% end %>

    <span id='open-modal-for-<%= permit.modal_id %>' style='color: #E58C00; cursor: pointer;', title='Editar permissão de acesso'>
      <i class='fa fa-pencil fa-fw fa-lg'></i>
    </span>
  </div>
</div>

<%= content_for :body_bottom do %>
  <%= render partial: 'permissions/edit', locals: { permit: permit, modal_id: "edit-#{permit.modal_id}" } %>
<% end %>

<%= content_for :js do %>
  var modal<%= permit.modal_id %> = $('#edit-<%= permit.modal_id %>');
  $('#open-modal-for-<%= permit.modal_id %>').on('click', function() {
    modal<%= permit.modal_id %>.modal('toggle', $(this));
  })
<% end %>