config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :home, only: :index

  resources :folders, except: [:new, :edit] do
    member do
      post 'create', as: :new_inner
      get  :manage
    end

    resources :access_permits, only: [:create, :update, :destroy]
  end

  resources :files, only: [:destroy] do
    post :upload, on: :collection

    member do
      get  :download
      post :toggle_lock
    end
  end

  resource :current_user, only: [:update], controller: :current_user do
    collection do
      get   :profile
      put   :update_password
      patch :update_password
    end
  end

  resource :control_panel, only: :show, controller: :control_panel do
    resources :users, except: :show do
      member do
        put   :update_password
        patch :update_password
      end
    end

    resources :contacts, only: [:index, :create, :destroy] do
      member do
        post :mark_as_processed
        post :mark_as_unprocessed
      end
    end
  end

  root 'home#index'
end

app/views/layouts/_dropdown_menu.html.erb
<div class='dropdown'>
  <div class='dropdown-toggle' data-toggle='dropdown'>
    <span class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
      <i class="fa fa-user fa-stack-1x"></i>
    </span>
  </div>
  <ul class='dropdown-menu dropdown-menu-right'>
    <li class='dropdown-header'>
      <h5>
        <div><%= current_user.name %></div>
        <div class='text-sm margin-t-sm'>
          <%= current_user.email %>
        </div>
      </h5>
    </li>
    <li><%= link_to 'Meu Perfil', profile_current_user_path %></li>

    <li role='separator' class='divider'></li>

    <li><%= link_to 'Cloud Storage', folders_path %></li>
    <% if policy(:control_panel).show? %>
      <li><%= link_to 'Painel de Controle', control_panel_path %></li>
    <% end %>

    <li role='separator' class='divider'></li>

    <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <%= content_tag :div, :id => 'flash-holder' do %>
    <% flash.each do |name, msgs| %>
      <% next if name == 'timedout' %>
      <%= content_tag :div, :class => name do %>
        <% Array(msgs).uniq.each do |msg| %>
          <%= content_tag :p, msg %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_side_menu.html.erb
<div id='side-menu' class='padding-lg'>
  <ul class='list-unstyled text-xl'>
    <li><%= link_to 'Usuários', control_panel_users_path, id: 'link-to-users' %></li>
    <li><%= link_to 'Contatos', control_panel_contacts_path, id: 'link-to-contacts' %></li>
  </ul>
</div>

app/views/layouts/_top_bar.html.erb
<div id='top-bar'>
  <div class='pull-right'>
    <% if user_signed_in? %>
      <%= render partial: 'layouts/dropdown_menu' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloud - Staysafe</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/top_bar' %>
    <div id="main">
      <%= render partial: 'layouts/flash_messages' %>
      <div id='content'>
        <%= yield %>
      </div>
    </div>
    <%= yield :body_bottom %>
  </body>
</html>

<script type="text/javascript">
  $(function(){
    <%= yield :js %>
  });
</script>

app/views/layouts/control_panel.html.erb
<%= extends :application do %>
  <div id='cp-wrapper'>
    <h1 id='cp-header' class='margin-o padding-v-md align-center'>Painel de Controle</h1>
    <div id='cp-body'>
      <%= render partial: 'layouts/side_menu' %>
      <div id='cp-content'>
        <div class="padding-xxl">
          <div class="panel panel-default margin-b-o padding-xxl">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloud - Staysafe</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render partial: 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>